# Generated by Django 4.0.3 on 2022-03-25 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gym',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('gym_details', models.CharField(default='WHY PURE GYM', max_length=255)),
                ('gym_link', models.URLField(default='https://www.puregym.com/', max_length=255)),
                ('description', models.CharField(max_length=355)),
                ('quality', models.CharField(max_length=355)),
                ('access', models.CharField(max_length=355)),
                ('network', models.CharField(max_length=355)),
                ('contract', models.CharField(max_length=355)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
